### PR TITLE
change-sidebar

### PR DESCRIPTION
**Pull request by Fahmiali99**
change sidebar and dasboard success

### CODE REVIEW

**Comment by Fahmiali99** [comment]
bayy cek

**Comment by Fahmiali99** [comment]
oiii

**Comment by Ubayhee0774** [comment]
oke mii

**Review by Ubayhee0774 — COMMENTED** [review]
udah bagus mi

**Comment by Fahmiali99** [comment]
okei, apa lagi ya yg mau di ganti?

**Pull request merged**
